apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elk
  labels:
    location: local
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/raynear/Project/var/persistentVolume

